language: c
sudo: false
env:
  global:
    - PATH=$HOME/miniconda/bin:$PATH
matrix:
  include:
    - os: linux
      python : "2.7"
      env: CONDA_PY=27  CONDA_NPY=19
    - os: linux
      python : "2.7"
      env: CONDA_PY=27  CONDA_NPY=110
before_install:
  - tools/install_miniconda.sh
  - conda config --set always_yes true
  - conda config --add channels omnia
  - conda install conda-build nose
script:
  - conda build -q conda-recipe
after_success:
  - pip install coveralls
  - coveralls
