package:
  name: pytram
  version: !!str dev

source:
  path: ..

requirements:
  build:
    - python
    - setuptools
    - numpy x.x
    - cython >=0.20

  run:
    - python
    - numpy x.x

test:
  requires:
    - nose
    - coverage ==4
  imports:
    - pytram
    - pytram._dtram
    - pytram._xtram

about:
  home: https://github.com/markovmodel/pytram
  license: BSD License
  summary: 'The TRAM package'
